In [2]:
import pandas as pd
import requests
import json
import time
from git import Repo

In [3]:
df = pd.read_csv("../../louvain/project_id_mapping.csv")
df

     Unnamed: 0               project name  project id
0             0                 peckshield           1
1             1                perifinance           2
2             2                  arenaswap           3
3             3                     cykura           4
4             4                   wigoswap           5
..          ...                        ...         ...
574         574            apollox-finance         575
575         575             alpaca-finance         576
576         576              boggedfinance         577
577         577           hodltreeprotocol         578
578         578  CryptoDevelopmentServices         579

[579 rows x 3 columns]

In [4]:
m = {}
for k,v in df.iterrows():
  m[v[2]] = v[1]

In [5]:
df2 = pd.read_csv("../../louvain/graph_node2comm_level2_merged")
df2

        0 0
0      1 36
1      2 19
2      3 71
3      4 19
4       5 1
..      ...
574  575 90
575  576 19
576  577 36
577  578 19
578  579 19

[579 rows x 1 columns]

In [6]:
m2 = {}
for ind,row in df2.iterrows():
  splitting = row[0].split(" ")
  node = int(splitting[0])
  cluster = int(splitting[1])

  if cluster not in m2:
    m2[cluster] = []
  m2[cluster].append(node)

In [7]:
m2[19]

[2,
 4,
 6,
 23,
 24,
 25,
 32,
 34,
 35,
 38,
 45,
 46,
 56,
 57,
 58,
 67,
 68,
 70,
 71,
 72,
 73,
 74,
 80,
 83,
 89,
 101,
 114,
 121,
 125,
 130,
 137,
 151,
 160,
 161,
 175,
 177,
 185,
 189,
 190,
 195,
 197,
 200,
 203,
 204,
 207,
 219,
 225,
 229,
 233,
 242,
 243,
 245,
 248,
 257,
 265,
 269,
 270,
 277,
 284,
 288,
 289,
 294,
 296,
 298,
 299,
 304,
 305,
 308,
 309,
 315,
 333,
 334,
 338,
 339,
 342,
 346,
 350,
 355,
 364,
 365,
 369,
 370,
 372,
 373,
 379,
 387,
 395,
 397,
 406,
 407,
 408,
 415,
 416,
 423,
 425,
 433,
 435,
 441,
 455,
 456,
 458,
 464,
 465,
 466,
 474,
 475,
 477,
 478,
 486,
 487,
 490,
 491,
 508,
 516,
 533,
 538,
 540,
 542,
 544,
 546,
 550,
 562,
 576,
 578,
 579]

In [8]:
username = "abhilashdzr"
token = "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"
gh_session = requests.Session()
gh_session.auth = (username, token)

In [10]:
common = "https://github.com/"
api_url = "https://api.github.com"

for i in m2[19]: 
    print(m[i])
    github_owner = common + str(m[i])

    url = api_url + f'/users/{str(m[i])}/repos'

    page = 1
    another_page = True
    repo_list = []
    try:
        while another_page:
            gh_session.params = {'page':page, 'per-page':100}
            r = gh_session.get(url)

            json_response = json.loads(r.text)
            for each in json_response:
                repo_name = each["name"]
                clone_url = github_owner+"/"+repo_name+".git"
                print(repo_name)
                if each["fork"] is not True: 
                    Repo.clone_from(clone_url,f"/media/abhilash/DATA/BTP_Project/cluster2/{m[i]}/{repo_name}")
                    time.sleep(5)
            if 'next' in r.links:
                page +=1
                time.sleep(500)
            else:
                page = 1
                another_page = False

    except:
        pass

perifinance
cykura
ZunamiLab
metavaultorg
candlegenie
BenTokenFinance
mean-dao
DODOEX
risqprotocol
bifrost-platform
PositionExchange
zenlinkpro
cronaswap
Switcheo
Polkamarkets
autoshark-finance
celer-network
muuu-finance
polydex-fi
MagicBallSwap
zoomswap
peakdefi
moneyTulip
GoldPesa
scream-finance
DefiKingdoms
augmented-finance
Layer3Org
annexfinance
typhoonnetwork
BeamSwap
bamboo-defi
BetSwirl
TrustFiNetwork
Snowball-Finance
DoubleClub
allbridge-io
ovnstable
AlpacaCity
FdogeFinance
LithiumSwapTech
ShibaNova
cougarswap
FarmersOnlyFi
mobiusAMM
impactMarket
devilfinanceio
betSwirl
WePiggy
darkcryptofi
whale-swap
dinosaur-eggs
RelayChain
hunnyfinance
claimswap
sturdyfi
darkcryptofinance
everrise-ecosystem
moonpotdev
tetu-io
OmniDexFinance
tranchess
bankrollnetwork
NearDeFi
SiriusFinance
timeleapfinance
ToadNetwork
popcorndao
tendieswap
united-farmers-finance
nextypefinance
aldrin-exchange
SiberianSwap-Finance
beefyfinance
deri-protocol
HuckleberryDEX
RedChillies-Core
ram-protocol
persistenceOne
Benqi-fi
beethovenxfi
chichicoding
singularfarm
stellaswap
Folks-Finance
MinotaurMoney
idexio
thefortube
WardenSwap
ZestProtocol
NemesisDao
polycatfi
symbiosis-finance
inthenextversion
BendDAO
babyswap
cexiswap
NestedFi
kwikswap
ringfi
farmersonlydefi
dante-finance
BarbershopFinance
versa-finance-dev
OpenLeverageDev
OtterClam
ZeroSwapLabs
buffaloswap
tokenjenny
acorn-finance
Aircoin-official
saddle-finance
CycleProtocol
iotexproject
kalmar-io
Good-Ghosting
omni-corp-protocols
alexgo-io
xcarnival
Convergence-Finance
RenovJ
HuckleberryDex
alpaca-finance
hodltreeprotocol
CryptoDevelopmentServices